export const gameConfig = {
  background: {
    bg: {
      tex: "background",
      x: 0,
      y: 0,
    },
  },
  UI: {
    bg: {
      x: 0,
      y: 600,
      width: 1280,
      height: 70,
      round: 15,
      alpha: 0.6,
      color: 0x000000,
    },
    balanceTitle: {
      style: {
        dropShadow: true,
        dropShadowAlpha: 0.2,
        dropShadowBlur: 12,
        dropShadowDistance: 7,
        fill: "#ededed",
        fontSize: 20,
        fontWeight: "bolder",
        strokeThickness: 1,
      },
      text: "BALANCE",
      x: 100,
      y: 620,
    },

    balance: {
      style: {
        dropShadow: true,
        dropShadowAlpha: 0.2,
        dropShadowBlur: 12,
        dropShadowDistance: 7,
        fill: "#ededed",
        fontSize: 20,
        fontWeight: "bolder",
        strokeThickness: 1,
      },
      text: "0",
      x: 100,
      y: 650,
    },
  },
  popup: {
    bg: {
      x: 340,
      y: 100,
      width: 1280 / 2,
      height: 400,
      round: 15,
      alpha: 0.6,
      color: 0x000000,
    },
    texts: [
      {
        text: "YOU WON",
        x: 1280 / 2,
        y: 140,
        style: {
          dropShadow: true,
          dropShadowAlpha: 0.2,
          dropShadowBlur: 12,
          dropShadowDistance: 7,
          fill: "#ededed",
          fontSize: 30,
          fontWeight: "bolder",
          strokeThickness: 1,
        },
      },
      {
        text: "WHEEL FEATURE",
        x: 1280 / 2,
        y: 180,
        style: {
          dropShadow: true,
          dropShadowAlpha: 0.2,
          dropShadowBlur: 12,
          dropShadowDistance: 7,
          fill: "#ededed",
          fontSize: 40,
          fontWeight: "bolder",
          strokeThickness: 1,
        },
      },
    ],
    wheelPeaces: 8,
    wheelPeace: {
      tex: "wheel-slice",
      x: 0,
      y: 0,
      anchor: 0,
      scale: 0.3,
      alpha: 1,
      angle: 40,
      pivot: { x: 370 / 2, y: 480 },
    },
    wheelsPointer: {
      tex: "pointer",
      x: 0,
      y: -130,
      anchor: 0.5,
      scale: 0.7,
      alpha: 1,
    },
    wheelsCenter: {
      tex: "wheel-center",
      x: 1280 / 2,
      y: 300,
      anchor: 0.5,
      scale: 0.7,
      alpha: 1,
    },
    nextButton: {
      container: {
        x: 650,
        y: 450,
      },
      bg: {
        x: 0,
        y: 0,
        width: 250,
        height: 50,
        round: 15,
        alpha: 1,
        color: 0xffffff,
      },

      text: {
        text: "CLICK TO CONTINUE",
        x: 125,
        y: 25,
        style: {
          fill: "#181818",
          fontSize: 20,
          fontWeight: "bolder",
        },
      },
    },
    winBg: {
      x: 0,
      y: 0,
      width: 1280,
      height: 720,
      round: 15,
      alpha: 0.6,
      color: 0x000000,
    },
    winText: {
      text: "YOU WON X CREDITS",
      x: 1280 / 2,
      y: 180,
      style: {
        dropShadow: true,
        dropShadowAlpha: 0.2,
        dropShadowBlur: 12,
        dropShadowDistance: 7,
        fill: "#ededed",
        fontSize: 40,
        fontWeight: "bolder",
        strokeThickness: 1,
      },
    },
    nextWinButton: {
      container: {
        x: 650,
        y: 550,
      },
      bg: {
        x: 0,
        y: 0,
        width: 250,
        height: 50,
        round: 15,
        alpha: 1,
        color: 0xffffff,
      },

      text: {
        text: "TAKE WIN",
        x: 125,
        y: 25,
        style: {
          fill: "#181818",
          fontSize: 20,
          fontWeight: "bolder",
        },
      },
    },
    emitter: {
      coin: {
        alpha: {
          start: 1,
          end: 1,
        },
        scale: {
          start: 0.1,
          end: 1,
        },
        speed: {
          start: 1000,
          end: 200,
        },
        acceleration: {
          x: 0,
          y: 2000,
        },
        startRotation: {
          min: 250,
          max: 290,
        },
        rotationSpeed: {
          min: 0,
          max: 0,
        },
        lifetime: {
          min: 5,
          max: 10,
        },
        blendMode: 'normal',
        frequency: 0.025,
        emitterLifetime: 0,
        maxParticles: 1000,
        pos: {
          x: 1280/2,
          y: 550,
        },
        addAtBack: false,
        spawnType: 'circle',
        spawnCircle: {
          x: 0,
          y: 0,
          r: 0,
        },
      },
    },
    emitterTex:['coin-anim-01','coin-anim-02','coin-anim-03','coin-anim-04','coin-anim-05','coin-anim-06',]
  },
  Wheel: {
    wheelTitle: {
      style: {
        dropShadow: true,
        dropShadowAlpha: 0.2,
        dropShadowBlur: 12,
        dropShadowDistance: 7,
        fill: "#ededed",
        fontSize: 60,
        fontWeight: "bolder",
        strokeThickness: 1,
      },
      text: "BONUS WHEEL",
      x: 1000,
      y: 250,
    },
    wheelPeaces: 8,
    wheelOffest: 40,
    wheelsCenter: {
      tex: "wheel-center",
      x: 440,
      y: 300,
      anchor: 0.5,
      scale: 0.7,
      alpha: 1,
    },
    wheelPeace: {
      tex: "wheel-slice",
      x: 0,
      y: 0,
      anchor: 0,
      scale: 0.8,
      alpha: 1,
      angle: 40,
      pivot: { x: 370 / 2, y: 480 },
      text: {
        text: "NO LIMIT",
        x: 190,
        y: 100,
        style: {
          fill: "#ff0000",
          fontSize: 20,
          fontWeight: "bolder",
        },
      },
    },
    wheelsPointer: {
      tex: "pointer",
      x: 443,
      y: 50,
      anchor: 0.5,
      scale: 1,
      alpha: 1,
    },
    spinButton: {
      container: {
        x: 1000,
        y: 350,
      },
      bg: {
        x: 0,
        y: 0,
        width: 150,
        height: 50,
        round: 15,
        alpha: 1,
        color: 0xffffff,
      },

      text: {
        text: "SPIN",
        x: 75,
        y: 25,
        style: {
          fill: "#181818",
          fontSize: 20,
          fontWeight: "bolder",
        },
      },
    },
  },
};
